#!/usr/bin/env php
<?php

require_once __DIR__ . '/loader.php';

use framework\App;
use framework\exceptions\CommandNotFoundException;

$args = get_args();

try {
    $app = new App();
    $app->handle($args);
} catch (CommandNotFoundException $e) {
    echo abort($e->getCode(), $e->getMessage());
}