#!/usr/bin/env php
<?php

require_once __DIR__ . '/loader.php';

use Framework\App;
use framework\exceptions\CommandNotFoundException;

$args = get_args();

try {
    $app = new App();
    $app->handle($args);
} catch (CommandNotFoundException $e) {
    abort($e->getCode(), $e->getMessage());
}